version: '3.1'

services:

  db:
    container_name: my_mariadb_container
    image: mariadb:10.4
    volumes:
      - ./mariadb-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ViN10020
    ports:
      - 3308:3306


  adminer:
    container_name: my_adminer_container
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 9080:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # Interface utilisateur Web
      - "1025:1025"  # Port SMTP

  spring-boot-app:
    image: projet-backend-0.0.1-snapshot:latest
    ports:
      - "8081:8080"
    depends_on:
        - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/calcul_formes_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ViN10020
