version: '3.1'

services:

  db:
    container_name: my_mysql_container
    image: mysql:8.0.34
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ViN10020
    ports:
      - 3308:3306

  adminer:
    container_name: my_adminer_container
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - 9080:8080

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '9081:80'
      - '9025:25'

  spring-boot-app:
    image: openjdk:11-jdk
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/calcul_formes_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ViN10020
